name: Run 9Hits Viewer in Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 часов
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download 9Hits Viewer from Google Drive
      run: |
        Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=1c6njvmYU0C30isOSUEVZKcv8GXl6E0DH" -OutFile "9hitsviewer.zip" -ErrorAction Stop
        Expand-Archive -Path "9hitsviewer.zip" -DestinationPath "." -Force -ErrorAction Stop
        Write-Output "9Hits Viewer downloaded and extracted from Google Drive"
      shell: powershell

    - name: Run 9Hits Viewer
      run: |
        Start-Process -FilePath "./9HitsViewer.exe" -ArgumentList "--token ${{ secrets.NINEHITS_TOKEN }}" -NoNewWindow -RedirectStandardOutput "9hits.log" -RedirectStandardError "9hits_error.log"
        Start-Sleep -Seconds 60 # Ждём 60 секунд для вывода
        Write-Output "9Hits Viewer started. Output:"
        Get-Content -Path "9hits.log" -ErrorAction SilentlyContinue
        Write-Output "Errors (if any):"
        Get-Content -Path "9hits_error.log" -ErrorAction SilentlyContinue
      shell: powershell

    - name: Keep alive
      run: |
        Write-Output "Server is running. 9Hits Viewer is working in the background."
        Start-Sleep -Seconds 21600 # 6 часов
      shell: powershell
