name: Windows Server

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run a simple command
      run: |
        Write-Output "Hello from Windows Server!"
        Get-ChildItem Env:
    ```

- `runs-on: windows-latest` указывает, что будет использоваться последняя версия Windows (обычно Windows Server 2022).
- `on: [push, workflow_dispatch]` позволяет запускать сервер при пуше в репозиторий или вручную через интерфейс GitHub.











