name: Windows Server with RDP via playit.gg

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 часов
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download playit.gg
      run: |
        Invoke-WebRequest -Uri "https://playit.gg/downloads/playit-win_64.exe" -OutFile "playit.exe" -ErrorAction Stop
        Write-Output "playit.gg downloaded"

    - name: Run playit.gg and enable RDP
      run: |
        # Запускаем playit.gg (предполагаем, что он уже настроен на хосте с туннелем)
        Start-Process -FilePath "./playit.exe" -NoNewWindow -RedirectStandardOutput "playit.log"
        Start-Sleep -Seconds 10 # Даём время на подключение

        # Включаем RDP
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0 -ErrorAction Stop
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction Stop
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1 -ErrorAction Stop
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd123" -Force) -ErrorAction Stop
        Write-Output "RDP enabled"

    - name: Display playit.gg tunnel info
      run: |
        Write-Output "Use your playit.gg tunnel address from the client: [IP:PORT]"
        Write-Output "Username: runneradmin"
        Write-Output "Password: P@ssw0rd123"

    - name: Keep alive
      run: |
        Write-Output "Server is running. Connect now!"
        Start-Sleep -Seconds 21600 # 6 часов
