name: Setup Docker and Run 9hits

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Docker Engine
      run: |
        # Устанавливаем Docker Engine для Windows Server
        Invoke-WebRequest -Uri https://download.docker.com/win/stable/Docker%20for%20Windows%20Server%202019.zip -OutFile DockerForWindows.zip
        Expand-Archive -Path DockerForWindows.zip -DestinationPath "C:\Program Files\Docker"
        Write-Output "Docker Engine installed."

    - name: Start Docker Engine
      run: |
        Start-Process "C:\Program Files\Docker\docker.exe" -ArgumentList "daemon" -Wait
        Write-Output "Docker Engine started."

    - name: Pull Docker Image 9hitste/app
      run: |
        # Загружаем образ с Docker Hub
        docker pull 9hitste/app
        Write-Output "Docker image 9hitste/app pulled."

    - name: Run 9hits Docker Container
      run: |
        # Запускаем контейнер с нужными параметрами, используя --network=bridge
        docker run -d --network=bridge --name=9hits 9hitste/app /nh.sh --token=dcd7ea6c4acdf7a3d50d78a50ee329a1 --system-session --allow-crypto=no
        Write-Output "Docker container 9hits started."

    - name: Verify Docker Container Running
      run: |
        # Проверяем, что контейнер работает
        docker ps
        Write-Output "Docker container is running."









