name: Setup Playit.gg Tunnel for RDP

on:
  push:
    branches:
      - main

jobs:
  setup-tunnel:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download playit.gg client
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "playit.exe" -ErrorAction Stop
        Write-Output "Playit.gg client downloaded successfully"

    - name: Run playit.gg and enable RDP tunnel
      run: |
        Start-Process -FilePath "./playit.exe" -ArgumentList "tcp 3389" -NoNewWindow
        Write-Output "Playit.gg tunnel started for RDP"

    - name: Display RDP tunnel information
      run: |
        Write-Output "Use the Playit.gg tunnel IP and port to connect via RDP."
        Write-Output "IP and Port will be available in the Playit logs."

    - name: Wait for Playit.gg tunnel to establish
      run: |
        Start-Sleep -Seconds 60
        Write-Output "Playit.gg tunnel established successfully."

