name: Windows Server with RDP via playit.gg

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 часов
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0 -ErrorAction Stop
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction Stop
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1 -ErrorAction Stop
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd123" -Force) -ErrorAction Stop
        Write-Output "RDP enabled successfully"

    - name: Display connection info
      run: |
        Write-Output "Use your playit.gg tunnel address from the client (e.g., 123.45.67.89:54321)"
        Write-Output "Username: runneradmin"
        Write-Output "Password: P@ssw0rd123"

    - name: Keep alive
      run: |
        Write-Output "Server is running. Connect now!"
        Start-Sleep -Seconds 21600 # 6 часов
