name: Setup Windows Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      remote_desktop_code:
        description: 'Enter your Google Remote Desktop code'
        required: true
        type: string
      remote_desktop_pin:
        description: 'Enter your Google Remote Desktop PIN'
        required: true
        type: string

jobs:
  setup-windows-server:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install Google Chrome
      run: choco install googlechrome -y

    - name: Install Google Remote Desktop
      run: choco install chromeremotedesktop -y

    - name: Configure Google Remote Desktop
      run: |
        $env:CHROME_REMOTE_DESKTOP_HOST = "${{ github.event.inputs.remote_desktop_code }}"
        $env:CHROME_REMOTE_DESKTOP_PIN = "${{ github.event.inputs.remote_desktop_pin }}"
        Start-Process "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remotedesktophost.exe" -ArgumentList "--start-host --code=$env:CHROME_REMOTE_DESKTOP_HOST --pin=$env:CHROME_REMOTE_DESKTOP_PIN" -NoNewWindow -Wait

    - name: Install other required software
      run: |
        choco install some-other-software -y

    - name: Finalize setup
      run: |
        # Add additional setup steps here if needed
