name: Setup Chrome Remote Desktop

on:
  workflow_dispatch:
    inputs:
      crd_code:
        description: 'Chrome Remote Desktop authorization code (e.g., 4/0AX4XfW...)'
        required: true
      pin_code:
        description: 'PIN code for Chrome Remote Desktop access'
        required: true

jobs:
  setup_crd:
    runs-on: windows-latest
    steps:
    - name: Install Google Chrome
      run: |
        Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe" -OutFile "ChromeSetup.exe"
        Start-Process -FilePath "ChromeSetup.exe" -ArgumentList "/silent /install" -Wait

    - name: Install Chrome Remote Desktop Host
      run: |
        Invoke-WebRequest -Uri "https://dl.google.com/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "CRDHost.msi"
        Start-Process -FilePath "msiexec.exe" -ArgumentList "/i CRDHost.msi /quiet" -Wait

    - name: Configure Chrome Remote Desktop
      run: |
        $env:CRD_CODE = '${{ github.event.inputs.crd_code }}'
        $env:PIN_CODE = '${{ github.event.inputs.pin_code }}'
        Start-Process -FilePath "$env:ProgramFiles\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" -ArgumentList "--code=$env:CRD_CODE --redirect-url=https://remotedesktop.google.com/_/oauthredirect --name=$env:COMPUTERNAME --pin=$env:PIN_CODE" -Wait




